import React from 'react';
import ReactDOM from 'react-dom/client';

//Building a app like Swiggy

/** 
 * Homepage
    - Logo
    - Nav-items

 * Body
    - Search
    - Restuarent container
        -Restuarent card
            - Img
            - Cusines
            - ratings
            - delivery time

* Footer
    - Copyright
    - Links
    - Address
    - Contact
*/

/**
 * Api copied from the network call of swiggy 
 * installed json viewer extension
 * 
 */
const resList = [
    { "info": { "id": "23696", "name": "McDonald's", "cloudinaryImageId": "bb7ae131544c7d37e10fc5faf76f09d6", "locality": "Kukatpally", "areaName": "Kukatpally", "costForTwo": "₹400 for two", "cuisines": ["Burgers", "Beverages", "Cafe", "Desserts"], "avgRating": 4.2, "parentId": "630", "avgRatingString": "4.2", "totalRatingsString": "10K+", "sla": { "deliveryTime": 22, "lastMileTravel": 3.8, "serviceability": "SERVICEABLE", "slaString": "22 mins", "lastMileTravelString": "3.8 km", "iconType": "ICON_TYPE_EMPTY" }, "availability": { "nextCloseTime": "2023-12-29 03:45:00", "opened": true }, "badges": { "textExtendedBadges": [{ "iconId": "guiltfree/GF_Logo_android_3x", "shortDescription": "options available", "fontColor": "#7E808C" }] }, "isOpen": true, "type": "F", "badgesV2": { "entityBadges": { "imageBased": {}, "textBased": {}, "textExtendedBadges": { "badgeObject": [{ "attributes": { "description": "", "fontColor": "#7E808C", "iconId": "guiltfree/GF_Logo_android_3x", "shortDescription": "options available" } }] } } }, "aggregatedDiscountInfoV3": { "header": "40% OFF", "subHeader": "UPTO ₹80" }, "loyaltyDiscoverPresentationInfo": { "logoCtx": { "text": "BENEFITS", "logo": "v1634558776/swiggy_one/OneLogo_3x.png" }, "freedelMessage": "FREE DELIVERY" }, "differentiatedUi": { "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT", "differentiatedUiMediaDetails": { "mediaType": "ADS_MEDIA_ENUM_IMAGE", "lottie": {}, "video": {} } }, "reviewsSummary": {}, "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT", "restaurantOfferPresentationInfo": {} }, "analytics": {}, "cta": { "link": "https://www.swiggy.com/restaurants/mcdonalds-kukatpally-hyderabad-23696", "type": "WEBLINK" } },
    { "info": { "id": "222934", "name": "Istah - The Mediterranean Way", "cloudinaryImageId": "9a01f2935fcb5ae05426db8264062102", "locality": "Nizampet", "areaName": "Kukatpally", "costForTwo": "₹240 for two", "cuisines": ["Mediterranean", "Snacks", "Biryani", "Grill", "Kebabs", "Arabian", "Lebanese", "Beverages", "Desserts", "Italian", "Turkish"], "avgRating": 4.3, "parentId": "3518", "avgRatingString": "4.3", "totalRatingsString": "10K+", "sla": { "deliveryTime": 27, "lastMileTravel": 4.5, "serviceability": "SERVICEABLE", "slaString": "27 mins", "lastMileTravelString": "4.5 km", "iconType": "ICON_TYPE_EMPTY" }, "availability": { "nextCloseTime": "2023-12-28 23:30:00", "opened": true }, "badges": { "imageBadges": [{ "imageId": "v1690360529/Ratnesh_Badges/Only_on_swiggy_badge_4x.png", "description": "OnlyOnSwiggy" }], "textExtendedBadges": [{ "iconId": "guiltfree/GF_Logo_android_3x", "shortDescription": "options available", "fontColor": "#7E808C" }] }, "isOpen": true, "type": "F", "badgesV2": { "entityBadges": { "imageBased": { "badgeObject": [{ "attributes": { "description": "OnlyOnSwiggy", "imageId": "v1690360529/Ratnesh_Badges/Only_on_swiggy_badge_4x.png" } }] }, "textBased": {}, "textExtendedBadges": { "badgeObject": [{ "attributes": { "description": "", "fontColor": "#7E808C", "iconId": "guiltfree/GF_Logo_android_3x", "shortDescription": "options available" } }] } } }, "aggregatedDiscountInfoV3": { "header": "60% OFF", "subHeader": "UPTO ₹110" }, "loyaltyDiscoverPresentationInfo": { "logoCtx": { "text": "BENEFITS", "logo": "v1634558776/swiggy_one/OneLogo_3x.png" }, "freedelMessage": "FREE DELIVERY" }, "differentiatedUi": { "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT", "differentiatedUiMediaDetails": { "mediaType": "ADS_MEDIA_ENUM_IMAGE", "lottie": {}, "video": {} } }, "reviewsSummary": {}, "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT", "restaurantOfferPresentationInfo": {} }, "analytics": {}, "cta": { "link": "https://www.swiggy.com/restaurants/istah-the-mediterranean-way-nizampet-kukatpally-hyderabad-222934", "type": "WEBLINK" } },
    { "info": { "id": "340484", "name": "Millet Express", "cloudinaryImageId": "75f8103a06f57c043f26343fa42e23e2", "locality": "Kphb", "areaName": "Kukatpally", "costForTwo": "₹150 for two", "cuisines": ["Healthy Food", "South Indian", "North Indian", "Biryani", "Chinese", "Beverages"], "avgRating": 4.3, "parentId": "10639", "avgRatingString": "4.3", "totalRatingsString": "10K+", "sla": { "deliveryTime": 22, "lastMileTravel": 3.7, "serviceability": "SERVICEABLE", "slaString": "22 mins", "lastMileTravelString": "3.7 km", "iconType": "ICON_TYPE_EMPTY" }, "availability": { "nextCloseTime": "2023-12-29 00:00:00", "opened": true }, "badges": { "textExtendedBadges": [{ "iconId": "guiltfree/GF_Logo_android_3x", "shortDescription": "brand", "fontColor": "#7E808C" }] }, "isOpen": true, "type": "F", "badgesV2": { "entityBadges": { "imageBased": {}, "textBased": {}, "textExtendedBadges": { "badgeObject": [{ "attributes": { "description": "", "fontColor": "#7E808C", "iconId": "guiltfree/GF_Logo_android_3x", "shortDescription": "brand" } }] } } }, "aggregatedDiscountInfoV3": { "header": "₹100 OFF", "subHeader": "ABOVE ₹199", "discountTag": "FLAT DEAL" }, "loyaltyDiscoverPresentationInfo": { "logoCtx": { "text": "BENEFITS", "logo": "v1634558776/swiggy_one/OneLogo_3x.png" }, "freedelMessage": "FREE DELIVERY" }, "differentiatedUi": { "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT", "differentiatedUiMediaDetails": { "mediaType": "ADS_MEDIA_ENUM_IMAGE", "lottie": {}, "video": {} } }, "reviewsSummary": {}, "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT", "restaurantOfferPresentationInfo": {} }, "analytics": {}, "cta": { "link": "https://www.swiggy.com/restaurants/millet-express-kphb-kukatpally-hyderabad-340484", "type": "WEBLINK" } },
    { "info": { "id": "25407", "name": "Oven Story Pizza - Standout Toppings", "cloudinaryImageId": "f986df6f1a1fcf2ff24d2eaf44d570a7", "locality": "Jayanagar Colony Kaman", "areaName": "Venkat Nagar Colony", "costForTwo": "₹400 for two", "cuisines": ["Pizzas", "Pastas", "Italian", "Desserts", "Beverages"], "avgRating": 4.1, "parentId": "3534", "avgRatingString": "4.1", "totalRatingsString": "5K+", "sla": { "deliveryTime": 35, "lastMileTravel": 3, "serviceability": "SERVICEABLE", "slaString": "29-41 mins", "lastMileTravelString": "3.0 km", "iconType": "ICON_TYPE_EMPTY" }, "availability": { "nextCloseTime": "2023-12-28 23:59:00", "opened": true }, "badges": {}, "isOpen": true, "type": "F", "badgesV2": { "entityBadges": { "imageBased": {}, "textBased": {}, "textExtendedBadges": {} } }, "aggregatedDiscountInfoV3": { "header": "60% OFF", "subHeader": "UPTO ₹110" }, "loyaltyDiscoverPresentationInfo": { "logoCtx": { "text": "BENEFITS", "logo": "v1634558776/swiggy_one/OneLogo_3x.png" }, "freedelMessage": "FREE DELIVERY" }, "differentiatedUi": { "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT", "differentiatedUiMediaDetails": { "mediaType": "ADS_MEDIA_ENUM_IMAGE", "lottie": {}, "video": {} } }, "reviewsSummary": {}, "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT", "restaurantOfferPresentationInfo": {} }, "analytics": {}, "cta": { "link": "https://www.swiggy.com/restaurants/oven-story-pizza-standout-toppings-jayanagar-colony-kaman-venkat-nagar-colony-hyderabad-25407", "type": "WEBLINK" } },
    { "info": { "id": "80483", "name": "The Bowl Company", "cloudinaryImageId": "bb6049fae59b8a2413a9177eb0338b49", "locality": "Seven Hills Colony", "areaName": "Kukatpally", "costForTwo": "₹300 for two", "cuisines": ["Pan-Asian", "Continental", "North Indian", "Desserts", "American", "Asian", "Beverages", "Biryani", "Chinese", "European", "Grill", "Hyderabadi", "Indian", "Italian", "Kebabs", "Lucknowi", "Mediterranean", "Mexican", "Mughlai", "Oriental", "Pastas", "Punjabi", "Raja"], "avgRating": 4.1, "parentId": "4317", "avgRatingString": "4.1", "totalRatingsString": "10K+", "sla": { "deliveryTime": 29, "lastMileTravel": 4.5, "serviceability": "SERVICEABLE", "slaString": "29 mins", "lastMileTravelString": "4.5 km", "iconType": "ICON_TYPE_EMPTY" }, "availability": { "nextCloseTime": "2023-12-28 23:30:00", "opened": true }, "badges": { "imageBadges": [{ "imageId": "v1690360529/Ratnesh_Badges/Only_on_swiggy_badge_4x.png", "description": "OnlyOnSwiggy" }] }, "isOpen": true, "type": "F", "badgesV2": { "entityBadges": { "imageBased": { "badgeObject": [{ "attributes": { "description": "OnlyOnSwiggy", "imageId": "v1690360529/Ratnesh_Badges/Only_on_swiggy_badge_4x.png" } }] }, "textBased": {}, "textExtendedBadges": {} } }, "aggregatedDiscountInfoV3": { "header": "60% OFF", "subHeader": "UPTO ₹110" }, "loyaltyDiscoverPresentationInfo": { "logoCtx": { "text": "BENEFITS", "logo": "v1634558776/swiggy_one/OneLogo_3x.png" }, "freedelMessage": "FREE DELIVERY" }, "differentiatedUi": { "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT", "differentiatedUiMediaDetails": { "mediaType": "ADS_MEDIA_ENUM_IMAGE", "lottie": {}, "video": {} } }, "reviewsSummary": {}, "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT", "restaurantOfferPresentationInfo": {} }, "analytics": {}, "cta": { "link": "https://www.swiggy.com/restaurants/the-bowl-company-seven-hills-colony-kukatpally-hyderabad-80483", "type": "WEBLINK" } },
    { "info": { "id": "46881", "name": "Pista House Restaurant & Bakery", "cloudinaryImageId": "e3r7hfdwz8cwgqi6jfgc", "locality": "Kukatpally", "areaName": "Kukatpally", "costForTwo": "₹500 for two", "cuisines": ["Biryani", "North Indian", "Chinese", "Kebabs", "Mughlai", "Tandoor", "Desserts"], "avgRating": 4.1, "parentId": "457788", "avgRatingString": "4.1", "totalRatingsString": "10K+", "sla": { "deliveryTime": 29, "lastMileTravel": 5.7, "serviceability": "SERVICEABLE", "slaString": "29 mins", "lastMileTravelString": "5.7 km", "iconType": "ICON_TYPE_EMPTY" }, "availability": { "nextCloseTime": "2023-12-28 23:59:00", "opened": true }, "badges": { "textExtendedBadges": [{ "iconId": "guiltfree/GF_Logo_android_3x", "shortDescription": "options available", "fontColor": "#7E808C" }] }, "isOpen": true, "type": "F", "badgesV2": { "entityBadges": { "imageBased": {}, "textBased": {}, "textExtendedBadges": { "badgeObject": [{ "attributes": { "description": "", "fontColor": "#7E808C", "iconId": "guiltfree/GF_Logo_android_3x", "shortDescription": "options available" } }] } } }, "aggregatedDiscountInfoV3": { "header": "40% OFF", "subHeader": "UPTO ₹80" }, "loyaltyDiscoverPresentationInfo": { "logoCtx": { "text": "BENEFITS", "logo": "v1634558776/swiggy_one/OneLogo_3x.png" }, "freedelMessage": "FREE DELIVERY" }, "differentiatedUi": { "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT", "differentiatedUiMediaDetails": { "mediaType": "ADS_MEDIA_ENUM_IMAGE", "lottie": {}, "video": {} } }, "reviewsSummary": {}, "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT", "restaurantOfferPresentationInfo": {} }, "analytics": {}, "cta": { "link": "https://www.swiggy.com/restaurants/pista-house-restaurant-and-bakery-kukatpally-hyderabad-46881", "type": "WEBLINK" } },
    { "info": { "id": "16168", "name": "Rice Bowl", "cloudinaryImageId": "bbc8jc5tjpnmrjooym1h", "locality": "KPHB 6th Phase", "areaName": "Kukatpally", "costForTwo": "₹200 for two", "cuisines": ["North Indian", "South Indian"], "avgRating": 3.7, "parentId": "169302", "avgRatingString": "3.7", "totalRatingsString": "10K+", "sla": { "deliveryTime": 41, "lastMileTravel": 6, "serviceability": "SERVICEABLE", "slaString": "41 mins", "lastMileTravelString": "6.0 km", "iconType": "ICON_TYPE_EMPTY" }, "availability": { "nextCloseTime": "2023-12-29 00:00:00", "opened": true }, "badges": {}, "isOpen": true, "type": "F", "badgesV2": { "entityBadges": { "imageBased": {}, "textBased": {}, "textExtendedBadges": {} } }, "aggregatedDiscountInfoV3": { "header": "₹175 OFF", "subHeader": "ABOVE ₹449", "discountTag": "FLAT DEAL" }, "loyaltyDiscoverPresentationInfo": { "logoCtx": { "text": "BENEFITS", "logo": "v1634558776/swiggy_one/OneLogo_3x.png" }, "freedelMessage": "FREE DELIVERY" }, "differentiatedUi": { "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT", "differentiatedUiMediaDetails": { "mediaType": "ADS_MEDIA_ENUM_IMAGE", "lottie": {}, "video": {} } }, "reviewsSummary": {}, "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT", "restaurantOfferPresentationInfo": {} }, "analytics": {}, "cta": { "link": "https://www.swiggy.com/restaurants/rice-bowl-kphb-6th-phase-kukatpally-hyderabad-16168", "type": "WEBLINK" } },
    { "info": { "id": "24619", "name": "Domino's Pizza", "cloudinaryImageId": "wkfr1eulvokpdcqhhi6m", "locality": "Alluri Trade Center", "areaName": "Kukatpally", "costForTwo": "₹400 for two", "cuisines": ["Pizzas", "Italian", "Pastas", "Desserts"], "avgRating": 4.3, "parentId": "2456", "avgRatingString": "4.3", "totalRatingsString": "10K+", "sla": { "deliveryTime": 26, "lastMileTravel": 3.6, "serviceability": "SERVICEABLE", "slaString": "26 mins", "lastMileTravelString": "3.6 km", "iconType": "ICON_TYPE_EMPTY" }, "availability": { "nextCloseTime": "2023-12-28 23:59:00", "opened": true }, "badges": {}, "isOpen": true, "type": "F", "badgesV2": { "entityBadges": { "imageBased": {}, "textBased": {}, "textExtendedBadges": {} } }, "aggregatedDiscountInfoV3": { "header": "30% OFF", "subHeader": "UPTO ₹75" }, "loyaltyDiscoverPresentationInfo": { "logoCtx": { "text": "BENEFITS", "logo": "v1634558776/swiggy_one/OneLogo_3x.png" }, "freedelMessage": "FREE DELIVERY" }, "differentiatedUi": { "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT", "differentiatedUiMediaDetails": { "mediaType": "ADS_MEDIA_ENUM_IMAGE", "lottie": {}, "video": {} } }, "reviewsSummary": {}, "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT", "restaurantOfferPresentationInfo": {} }, "analytics": {}, "cta": { "link": "https://www.swiggy.com/restaurants/dominos-pizza-alluri-trade-center-kukatpally-hyderabad-24619", "type": "WEBLINK" } },
    { "info": { "id": "17097", "name": "KFC", "cloudinaryImageId": "f01666ac73626461d7455d9c24005cd4", "locality": "Kukatpally", "areaName": "Kukatpally", "costForTwo": "₹400 for two", "cuisines": ["Burgers", "Biryani", "American", "Snacks", "Fast Food"], "avgRating": 4.1, "parentId": "547", "avgRatingString": "4.1", "totalRatingsString": "10K+", "sla": { "deliveryTime": 25, "lastMileTravel": 4.7, "serviceability": "SERVICEABLE", "slaString": "25 mins", "lastMileTravelString": "4.7 km", "iconType": "ICON_TYPE_EMPTY" }, "availability": { "nextCloseTime": "2023-12-29 01:00:00", "opened": true }, "badges": {}, "isOpen": true, "type": "F", "badgesV2": { "entityBadges": { "imageBased": {}, "textBased": {}, "textExtendedBadges": {} } }, "aggregatedDiscountInfoV3": { "header": "EVERY ITEM", "subHeader": "@ ₹179" }, "loyaltyDiscoverPresentationInfo": { "logoCtx": { "text": "BENEFITS", "logo": "v1634558776/swiggy_one/OneLogo_3x.png" }, "freedelMessage": "FREE DELIVERY" }, "differentiatedUi": { "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT", "differentiatedUiMediaDetails": { "mediaType": "ADS_MEDIA_ENUM_IMAGE", "lottie": {}, "video": {} } }, "reviewsSummary": {}, "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT", "restaurantOfferPresentationInfo": {} }, "analytics": {}, "cta": { "link": "https://www.swiggy.com/restaurants/kfc-kukatpally-hyderabad-17097", "type": "WEBLINK" } },
    { "info": { "id": "156452", "name": "The Good Bowl", "cloudinaryImageId": "6e04be27387483a7c00444f8e8241108", "locality": "Jayanagar Colony Kaman", "areaName": "Venkat Nagar Colony", "costForTwo": "₹400 for two", "cuisines": ["Biryani", "Pastas", "Punjabi", "Desserts", "Beverages"], "avgRating": 3.9, "parentId": "7918", "avgRatingString": "3.9", "totalRatingsString": "1K+", "sla": { "deliveryTime": 23, "lastMileTravel": 3, "serviceability": "SERVICEABLE", "slaString": "23 mins", "lastMileTravelString": "3.0 km", "iconType": "ICON_TYPE_EMPTY" }, "availability": { "nextCloseTime": "2023-12-28 23:59:00", "opened": true }, "badges": {}, "isOpen": true, "type": "F", "badgesV2": { "entityBadges": { "imageBased": {}, "textBased": {}, "textExtendedBadges": {} } }, "aggregatedDiscountInfoV3": { "header": "60% OFF", "subHeader": "UPTO ₹110" }, "loyaltyDiscoverPresentationInfo": { "logoCtx": { "text": "BENEFITS", "logo": "v1634558776/swiggy_one/OneLogo_3x.png" }, "freedelMessage": "FREE DELIVERY" }, "differentiatedUi": { "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT", "differentiatedUiMediaDetails": { "mediaType": "ADS_MEDIA_ENUM_IMAGE", "lottie": {}, "video": {} } }, "reviewsSummary": {}, "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT", "restaurantOfferPresentationInfo": {} }, "analytics": {}, "cta": { "link": "https://www.swiggy.com/restaurants/the-good-bowl-jayanagar-colony-kaman-venkat-nagar-colony-hyderabad-156452", "type": "WEBLINK" } },
    { "info": { "id": "11114", "name": "Pizza Hut", "cloudinaryImageId": "2b4f62d606d1b2bfba9ba9e5386fabb7", "locality": "Hydernagar", "areaName": "Kukatpally", "costForTwo": "₹350 for two", "cuisines": ["Pizzas"], "avgRating": 3.7, "parentId": "721", "avgRatingString": "3.7", "totalRatingsString": "10K+", "sla": { "deliveryTime": 35, "lastMileTravel": 5, "serviceability": "SERVICEABLE", "slaString": "35 mins", "lastMileTravelString": "5.0 km", "iconType": "ICON_TYPE_EMPTY" }, "availability": { "nextCloseTime": "2023-12-28 23:00:00", "opened": true }, "badges": {}, "isOpen": true, "type": "F", "badgesV2": { "entityBadges": { "imageBased": {}, "textBased": {}, "textExtendedBadges": {} } }, "aggregatedDiscountInfoV3": { "header": "ITEMS", "subHeader": "AT ₹179" }, "loyaltyDiscoverPresentationInfo": { "logoCtx": { "text": "BENEFITS", "logo": "v1634558776/swiggy_one/OneLogo_3x.png" }, "freedelMessage": "FREE DELIVERY" }, "differentiatedUi": { "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT", "differentiatedUiMediaDetails": { "mediaType": "ADS_MEDIA_ENUM_IMAGE", "lottie": {}, "video": {} } }, "reviewsSummary": {}, "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT", "restaurantOfferPresentationInfo": {} }, "analytics": {}, "cta": { "link": "https://www.swiggy.com/restaurants/pizza-hut-hydernagar-kukatpally-hyderabad-11114", "type": "WEBLINK" } },
    { "info": { "id": "429123", "name": "Harley's Fine Baking", "cloudinaryImageId": "xuawff9uvxhlmfrrnxpe", "locality": "Food Courtin Bramaramba Theater", "areaName": "Nizampet & Pragathi Nagar", "costForTwo": "₹600 for two", "cuisines": ["Bakery", "Desserts"], "avgRating": 4.4, "parentId": "11126", "avgRatingString": "4.4", "totalRatingsString": "1K+", "sla": { "deliveryTime": 28, "lastMileTravel": 5, "serviceability": "SERVICEABLE", "slaString": "28 mins", "lastMileTravelString": "5.0 km", "iconType": "ICON_TYPE_EMPTY" }, "availability": { "nextCloseTime": "2023-12-29 02:00:00", "opened": true }, "badges": { "imageBadges": [{ "imageId": "newg.png", "description": "Gourmet" }] }, "isOpen": true, "type": "F", "badgesV2": { "entityBadges": { "imageBased": { "badgeObject": [{ "attributes": { "description": "Gourmet", "imageId": "newg.png" } }] }, "textBased": {}, "textExtendedBadges": {} } }, "aggregatedDiscountInfoV3": { "header": "20% OFF", "subHeader": "UPTO ₹50" }, "loyaltyDiscoverPresentationInfo": { "logoCtx": { "text": "BENEFITS", "logo": "v1634558776/swiggy_one/OneLogo_3x.png" }, "freedelMessage": "FREE DELIVERY" }, "differentiatedUi": { "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT", "differentiatedUiMediaDetails": { "mediaType": "ADS_MEDIA_ENUM_IMAGE", "lottie": {}, "video": {} } }, "reviewsSummary": {}, "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT", "restaurantOfferPresentationInfo": {} }, "analytics": {}, "cta": { "link": "https://www.swiggy.com/restaurants/harleys-fine-baking-food-courtin-bramaramba-theater-nizampet-and-pragathi-nagar-hyderabad-429123", "type": "WEBLINK" } },
    { "info": { "id": "392905", "name": "Theobroma", "cloudinaryImageId": "b033728dcb0101ceb19bff0e1e1f6474", "locality": "Kukatpally", "areaName": "Kukatpally", "costForTwo": "₹400 for two", "cuisines": ["Desserts"], "avgRating": 4.4, "parentId": "1040", "avgRatingString": "4.4", "totalRatingsString": "1K+", "sla": { "deliveryTime": 34, "lastMileTravel": 6.7, "serviceability": "SERVICEABLE", "slaString": "34 mins", "lastMileTravelString": "6.7 km", "iconType": "ICON_TYPE_EMPTY" }, "availability": { "nextCloseTime": "2023-12-28 23:00:00", "opened": true }, "badges": { "imageBadges": [{ "imageId": "newg.png", "description": "Gourmet" }] }, "isOpen": true, "type": "F", "badgesV2": { "entityBadges": { "imageBased": { "badgeObject": [{ "attributes": { "description": "Gourmet", "imageId": "newg.png" } }] }, "textBased": {}, "textExtendedBadges": {} } }, "aggregatedDiscountInfoV3": { "header": "40% OFF", "subHeader": "ABOVE ₹179", "discountTag": "FLAT DEAL" }, "loyaltyDiscoverPresentationInfo": { "logoCtx": { "text": "BENEFITS", "logo": "v1634558776/swiggy_one/OneLogo_3x.png" }, "freedelMessage": "FREE DELIVERY" }, "differentiatedUi": { "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT", "differentiatedUiMediaDetails": { "mediaType": "ADS_MEDIA_ENUM_IMAGE", "lottie": {}, "video": {} } }, "reviewsSummary": {}, "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT", "restaurantOfferPresentationInfo": {} }, "analytics": {}, "cta": { "link": "https://www.swiggy.com/restaurants/theobroma-kukatpally-hyderabad-392905", "type": "WEBLINK" } },
    { "info": { "id": "20346", "name": "Subway", "cloudinaryImageId": "1ace5fa65eff3e1223feb696c956b38b", "locality": "Bhagya nagar Colony", "areaName": "Venkat Nagar Colony", "costForTwo": "₹350 for two", "cuisines": ["Salads", "Snacks", "Desserts", "Beverages"], "avgRating": 4.1, "parentId": "2", "avgRatingString": "4.1", "totalRatingsString": "10K+", "sla": { "deliveryTime": 24, "lastMileTravel": 3.6, "serviceability": "SERVICEABLE", "slaString": "24 mins", "lastMileTravelString": "3.6 km", "iconType": "ICON_TYPE_EMPTY" }, "availability": { "nextCloseTime": "2023-12-29 00:00:00", "opened": true }, "badges": { "textExtendedBadges": [{ "iconId": "guiltfree/GF_Logo_android_3x", "shortDescription": "options available", "fontColor": "#7E808C" }] }, "isOpen": true, "type": "F", "badgesV2": { "entityBadges": { "imageBased": {}, "textBased": {}, "textExtendedBadges": { "badgeObject": [{ "attributes": { "description": "", "fontColor": "#7E808C", "iconId": "guiltfree/GF_Logo_android_3x", "shortDescription": "options available" } }] } } }, "loyaltyDiscoverPresentationInfo": { "logoCtx": { "text": "BENEFITS", "logo": "v1634558776/swiggy_one/OneLogo_3x.png" }, "freedelMessage": "FREE DELIVERY" }, "differentiatedUi": { "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT", "differentiatedUiMediaDetails": { "mediaType": "ADS_MEDIA_ENUM_IMAGE", "lottie": {}, "video": {} } }, "reviewsSummary": {}, "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT", "restaurantOfferPresentationInfo": {} }, "analytics": {}, "cta": { "link": "https://www.swiggy.com/restaurants/subway-bhagya-nagar-colony-venkat-nagar-colony-hyderabad-20346", "type": "WEBLINK" } },
    { "info": { "id": "76712", "name": "CakeZone", "cloudinaryImageId": "12ee141ef81c0312fa91cf9ef4b6733b", "locality": "Kukatpally Circle", "areaName": "HMT Satavahana Nagar", "costForTwo": "₹200 for two", "cuisines": ["Bakery", "Desserts", "Sweets", "Ice Cream"], "avgRating": 4.3, "parentId": "7003", "avgRatingString": "4.3", "totalRatingsString": "10K+", "sla": { "deliveryTime": 23, "lastMileTravel": 3.5, "serviceability": "SERVICEABLE", "slaString": "23 mins", "lastMileTravelString": "3.5 km", "iconType": "ICON_TYPE_EMPTY" }, "availability": { "nextCloseTime": "2023-12-29 00:00:00", "opened": true }, "badges": { "textExtendedBadges": [{ "iconId": "guiltfree/GF_Logo_android_3x", "shortDescription": "options available", "fontColor": "#7E808C" }] }, "isOpen": true, "type": "F", "badgesV2": { "entityBadges": { "imageBased": {}, "textBased": {}, "textExtendedBadges": { "badgeObject": [{ "attributes": { "description": "", "fontColor": "#7E808C", "iconId": "guiltfree/GF_Logo_android_3x", "shortDescription": "options available" } }] } } }, "aggregatedDiscountInfoV3": { "header": "60% OFF", "subHeader": "UPTO ₹120" }, "loyaltyDiscoverPresentationInfo": { "logoCtx": { "text": "BENEFITS", "logo": "v1634558776/swiggy_one/OneLogo_3x.png" }, "freedelMessage": "FREE DELIVERY" }, "differentiatedUi": { "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT", "differentiatedUiMediaDetails": { "mediaType": "ADS_MEDIA_ENUM_IMAGE", "lottie": {}, "video": {} } }, "reviewsSummary": {}, "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT", "restaurantOfferPresentationInfo": {} }, "analytics": {}, "cta": { "link": "https://www.swiggy.com/restaurants/cakezone-kukatpally-circle-hmt-satavahana-nagar-hyderabad-76712", "type": "WEBLINK" } },
    { "info": { "id": "14989", "name": "Faasos - Wraps, Rolls & Shawarma", "cloudinaryImageId": "af33b81798b11deba338e94b7585d348", "locality": "Jayanagar Colony Kaman", "areaName": "Venkat Nagar Colony", "costForTwo": "₹200 for two", "cuisines": ["Kebabs", "Fast Food", "Snacks", "American", "Healthy Food", "Desserts", "Beverages"], "avgRating": 3.8, "parentId": "21809", "avgRatingString": "3.8", "totalRatingsString": "10K+", "sla": { "deliveryTime": 25, "lastMileTravel": 3, "serviceability": "SERVICEABLE", "slaString": "25 mins", "lastMileTravelString": "3.0 km", "iconType": "ICON_TYPE_EMPTY" }, "availability": { "nextCloseTime": "2023-12-28 23:59:00", "opened": true }, "badges": { "textExtendedBadges": [{ "iconId": "guiltfree/GF_Logo_android_3x", "shortDescription": "options available", "fontColor": "#7E808C" }] }, "isOpen": true, "type": "F", "badgesV2": { "entityBadges": { "imageBased": {}, "textBased": {}, "textExtendedBadges": { "badgeObject": [{ "attributes": { "description": "", "fontColor": "#7E808C", "iconId": "guiltfree/GF_Logo_android_3x", "shortDescription": "options available" } }] } } }, "aggregatedDiscountInfoV3": { "header": "ITEMS", "subHeader": "AT ₹129" }, "loyaltyDiscoverPresentationInfo": { "logoCtx": { "text": "BENEFITS", "logo": "v1634558776/swiggy_one/OneLogo_3x.png" }, "freedelMessage": "FREE DELIVERY" }, "differentiatedUi": { "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT", "differentiatedUiMediaDetails": { "mediaType": "ADS_MEDIA_ENUM_IMAGE", "lottie": {}, "video": {} } }, "reviewsSummary": {}, "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT", "restaurantOfferPresentationInfo": {} }, "analytics": {}, "cta": { "link": "https://www.swiggy.com/restaurants/faasos-wraps-rolls-and-shawarma-jayanagar-colony-kaman-venkat-nagar-colony-hyderabad-14989", "type": "WEBLINK" } },
    { "info": { "id": "124164", "name": "Starbucks Coffee", "cloudinaryImageId": "258fe8a3577877fbfe064095ed1d9dc3", "locality": "Forum Mall", "areaName": "Kukatpally", "costForTwo": "₹400 for two", "cuisines": ["Beverages", "Cafe", "Snacks", "Desserts", "Bakery", "Ice Cream"], "avgRating": 4.2, "parentId": "195515", "avgRatingString": "4.2", "totalRatingsString": "1K+", "sla": { "deliveryTime": 35, "lastMileTravel": 6.7, "serviceability": "SERVICEABLE", "slaString": "35 mins", "lastMileTravelString": "6.7 km", "iconType": "ICON_TYPE_EMPTY" }, "availability": { "nextCloseTime": "2023-12-28 23:00:00", "opened": true }, "badges": { "textExtendedBadges": [{ "iconId": "guiltfree/GF_Logo_android_3x", "shortDescription": "options available", "fontColor": "#7E808C" }] }, "isOpen": true, "type": "F", "badgesV2": { "entityBadges": { "imageBased": {}, "textBased": {}, "textExtendedBadges": { "badgeObject": [{ "attributes": { "description": "", "fontColor": "#7E808C", "iconId": "guiltfree/GF_Logo_android_3x", "shortDescription": "options available" } }] } } }, "aggregatedDiscountInfoV3": { "header": "10% OFF", "subHeader": "ABOVE ₹900", "discountTag": "FLAT DEAL" }, "loyaltyDiscoverPresentationInfo": { "logoCtx": { "text": "BENEFITS", "logo": "v1634558776/swiggy_one/OneLogo_3x.png" }, "freedelMessage": "FREE DELIVERY" }, "differentiatedUi": { "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT", "differentiatedUiMediaDetails": { "mediaType": "ADS_MEDIA_ENUM_IMAGE", "lottie": {}, "video": {} } }, "reviewsSummary": {}, "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT", "restaurantOfferPresentationInfo": {} }, "analytics": {}, "cta": { "link": "https://www.swiggy.com/restaurants/starbucks-coffee-forum-mall-kukatpally-hyderabad-124164", "type": "WEBLINK" } },
    { "info": { "id": "363823", "name": "Wow! Momo", "cloudinaryImageId": "0984acc0ed7b914206dbbcb90297becc", "locality": "Kukatpally", "areaName": "Kukatpally", "costForTwo": "₹300 for two", "cuisines": ["Tibetan", "Healthy Food", "Asian", "Chinese", "Snacks", "Continental", "Desserts", "Beverages"], "avgRating": 4.1, "parentId": "1776", "avgRatingString": "4.1", "totalRatingsString": "1K+", "sla": { "deliveryTime": 29, "lastMileTravel": 5, "serviceability": "SERVICEABLE", "slaString": "29 mins", "lastMileTravelString": "5.0 km", "iconType": "ICON_TYPE_EMPTY" }, "availability": { "nextCloseTime": "2023-12-28 22:30:00", "opened": true }, "badges": {}, "isOpen": true, "type": "F", "badgesV2": { "entityBadges": { "imageBased": {}, "textBased": {}, "textExtendedBadges": {} } }, "aggregatedDiscountInfoV3": { "header": "ITEMS", "subHeader": "AT ₹99" }, "loyaltyDiscoverPresentationInfo": { "logoCtx": { "text": "BENEFITS", "logo": "v1634558776/swiggy_one/OneLogo_3x.png" }, "freedelMessage": "FREE DELIVERY" }, "differentiatedUi": { "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT", "differentiatedUiMediaDetails": { "mediaType": "ADS_MEDIA_ENUM_IMAGE", "lottie": {}, "video": {} } }, "reviewsSummary": {}, "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT", "restaurantOfferPresentationInfo": {} }, "analytics": {}, "cta": { "link": "https://www.swiggy.com/restaurants/wow-momo-kukatpally-hyderabad-363823", "type": "WEBLINK" } },
    { "info": { "id": "35538", "name": "Sweet Truth - Cake and Desserts", "cloudinaryImageId": "81cf6bfe2760a45a0caf2e28716ca4d7", "locality": "Jayanagar Colony Kaman", "areaName": "Venkat Nagar Colony", "costForTwo": "₹450 for two", "cuisines": ["Snacks", "Bakery", "Desserts", "Beverages"], "avgRating": 4.1, "parentId": "4444", "avgRatingString": "4.1", "totalRatingsString": "1K+", "sla": { "deliveryTime": 23, "lastMileTravel": 3, "serviceability": "SERVICEABLE", "slaString": "23 mins", "lastMileTravelString": "3.0 km", "iconType": "ICON_TYPE_EMPTY" }, "availability": { "nextCloseTime": "2023-12-28 23:59:00", "opened": true }, "badges": {}, "isOpen": true, "type": "F", "badgesV2": { "entityBadges": { "imageBased": {}, "textBased": {}, "textExtendedBadges": {} } }, "aggregatedDiscountInfoV3": { "header": "60% OFF", "subHeader": "UPTO ₹110" }, "loyaltyDiscoverPresentationInfo": { "logoCtx": { "text": "BENEFITS", "logo": "v1634558776/swiggy_one/OneLogo_3x.png" }, "freedelMessage": "FREE DELIVERY" }, "differentiatedUi": { "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT", "differentiatedUiMediaDetails": { "mediaType": "ADS_MEDIA_ENUM_IMAGE", "lottie": {}, "video": {} } }, "reviewsSummary": {}, "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT", "restaurantOfferPresentationInfo": {} }, "analytics": {}, "cta": { "link": "https://www.swiggy.com/restaurants/sweet-truth-cake-and-desserts-jayanagar-colony-kaman-venkat-nagar-colony-hyderabad-35538", "type": "WEBLINK" } },
    { "info": { "id": "3171", "name": "KS Bakers", "cloudinaryImageId": "6127cb288329ad1c9e988276914d48ad", "locality": "Kukatpally", "areaName": "Bhagyanagar Colony", "costForTwo": "₹250 for two", "cuisines": ["Bakery", "Pizzas", "Desserts", "Snacks", "Fast Food"], "avgRating": 4.1, "parentId": "574", "avgRatingString": "4.1", "totalRatingsString": "10K+", "sla": { "deliveryTime": 24, "lastMileTravel": 3.9, "serviceability": "SERVICEABLE", "slaString": "24 mins", "lastMileTravelString": "3.9 km", "iconType": "ICON_TYPE_EMPTY" }, "availability": { "nextCloseTime": "2023-12-28 22:45:00", "opened": true }, "badges": { "textExtendedBadges": [{ "iconId": "guiltfree/GF_Logo_android_3x", "shortDescription": "options available", "fontColor": "#7E808C" }] }, "isOpen": true, "type": "F", "badgesV2": { "entityBadges": { "imageBased": {}, "textBased": {}, "textExtendedBadges": { "badgeObject": [{ "attributes": { "description": "", "fontColor": "#7E808C", "iconId": "guiltfree/GF_Logo_android_3x", "shortDescription": "options available" } }] } } }, "aggregatedDiscountInfoV3": { "header": "₹100 OFF", "subHeader": "ABOVE ₹199", "discountTag": "FLAT DEAL" }, "loyaltyDiscoverPresentationInfo": { "logoCtx": { "text": "BENEFITS", "logo": "v1634558776/swiggy_one/OneLogo_3x.png" }, "freedelMessage": "FREE DELIVERY" }, "differentiatedUi": { "displayType": "ADS_UI_DISPLAY_TYPE_ENUM_DEFAULT", "differentiatedUiMediaDetails": { "mediaType": "ADS_MEDIA_ENUM_IMAGE", "lottie": {}, "video": {} } }, "reviewsSummary": {}, "displayType": "RESTAURANT_DISPLAY_TYPE_DEFAULT", "restaurantOfferPresentationInfo": {} }, "analytics": {}, "cta": { "link": "https://www.swiggy.com/restaurants/ks-bakers-kukatpally-bhagyanagar-colony-hyderabad-3171", "type": "WEBLINK" } }
];

const Header = () => {
    return (
        <div className="header">
            <div className="logo-container">
                <img src="https://img.freepik.com/free-vector/food-shopping-logo-template-design_460848-10299.jpg" alt="site logo" className="logo" />
            </div>
            <div className="nav-items">
                <ul>
                    <li>Homepage</li>
                    <li>About us</li>
                    <li>Contact us</li>
                    <li>Cart</li>
                </ul>
            </div>
        </div>
    )
}

const RestuarentCard = (props) => {

    const { resDetails } = props;
    const { name, cuisines, avgRating, sla } = resDetails?.info;
    console.log(cuisines);

    let top3Cusines;
    if (cuisines.length > 3) {
        top3Cusines = cuisines.slice(0, 3).join(',');
    }
    return (
        <div className='res-card'>
            <img src={"https://media-assets.swiggy.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_660/" + resDetails.info.cloudinaryImageId}
                alt="restaurent logo"
                className='res-logo'
            />
            <div className="res-details">
                <h3>{name}</h3>
                <h5>{(cuisines.length > 3) ? top3Cusines : cuisines.join(',')}</h5>
                <h5>{avgRating} Stars</h5>
                <h5>{sla.deliveryTime} Mins</h5>
            </div>
        </div>)
}

const Body = () => {
    return (<div className="body">
        <div className="res-container">
            <RestuarentCard resDetails={resList[0]} />
            <RestuarentCard resDetails={resList[1]} />
            <RestuarentCard resDetails={resList[2]} />
            <RestuarentCard resDetails={resList[3]} />
            <RestuarentCard resDetails={resList[5]} />
            <RestuarentCard resDetails={resList[6]} />
            <RestuarentCard resDetails={resList[7]} />
            <RestuarentCard resDetails={resList[8]} />
            <RestuarentCard resDetails={resList[9]} />
            <RestuarentCard resDetails={resList[10]} />
            <RestuarentCard resDetails={resList[11]} />
            <RestuarentCard resDetails={resList[12]} />
            <RestuarentCard resDetails={resList[13]} />
            <RestuarentCard resDetails={resList[14]} />
        </div >
    </div>)
}

const AppLayout = () => {
    return (
        <div>
            <Header />
            <Body />
        </div>
    );
}

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(<AppLayout />)
